### ISSUE TITLE
Ask user to when remove discussion is pressed

### ISSUE THREAD

**Issue by ParisNeo** [ParisNeo/lollms-webui#14]
When user deletes a discussion. It would be a good idea to ask him if he is sure before validating.
Also we need to make a way to select multiple discussions to remove zt once and an option to remove every thing.

**Comment by afzalzbr** [comment]
@ParisNeo, please assign the issue to me, and I can work on it.

**Comment by ParisNeo** [comment]
Go for it.

**Comment by ParisNeo** [comment]
Please start by pulling the latest version as there are core changes.
Best regards

**Comment by andzejsp** [comment]
done!

**Comment by d13g4** [comment]
i think that can be closed safely
