### ISSUE TITLE
Can't build binding on Windows and in effect can't load a model.

### ISSUE THREAD

**Issue by ramzeez88** [ParisNeo/lollms-webui#272]
## Expected Behavior
To load a model.

## Current Behavior
I run the webui.bat via cmd via anaconda venv.
Here is the message I get:

Checking models...
Virtual environment created and packages installed successfully.
Launching application...
Configuration file is very old. Replacing with default configuration
Added entries : [], removed entries:[]
 ******************* Building Binding from main Process *************************
Loading binding None install ON
Couldn't build binding.
unsupported operand type(s) for /: 'WindowsPath' and 'NoneType'
 ******************* Building mounted Personalities from main Process *************************
 english/generic/lollms
Loading from C:\gpt4all\GPT4All\env\lib\site-packages\lollms\personalities_zoo\english\generic\lollms
 ************ Personalities mounted (Main process) ***************************
Checking discussions database...
Please open your browser and go to http://localhost:9600 to view the ui
debug mode:false
Client connected
 ******************* Building Binding from generation Process *************************
Loading binding None install ON
Traceback (most recent call last):
  File "C:\gpt4all\GPT4All\api\__init__.py", line 222, in _rebuild_model
    self.binding = self.load_binding(self.config["binding_name"], install=True)
  File "C:\gpt4all\GPT4All\api\__init__.py", line 141, in load_binding
    binding_path = self.lollms_paths.bindings_zoo_path/binding_name
TypeError: unsupported operand type(s) for /: 'WindowsPath' and 'NoneType'
Couldn't build binding
unsupported operand type(s) for /: 'WindowsPath' and 'NoneType'
 ******************* Building mounted Personalities from generation Process *************************
 english/generic/lollms
 ************ Personalities mounted (Generation process) ***************************
Personality set successfully
Launching config verification thread
Launching cancel verification thread
Launching clear verification thread
No model loaded. Waiting for new configuration instructions
Listening on :http://localhost:9600

After selecting a GPt4all binding in the UI an then a model in model zoo I get a posivite message saying that the model has been selected but when I go to discussion and start the chat with any word I get an error message 'it seems that no model hase been loaded...'
What can be the solution to this issue ?

**Comment by boricuapab** [comment]
Im running into this issue as well

![errorLoadingModels](https://github.com/ParisNeo/lollms-webui/assets/61924816/5c6dc3ef-f48d-4e85-858f-43176a58265b)

**Comment by DigiTecK3D** [comment]
Also running into the same issue 
![image](https://github.com/ParisNeo/lollms-webui/assets/5471872/adf8d728-6044-4a30-8994-e265d2ef71a3)
and I'm also not seeing anything of a UI to work with when I open up the page.
![image](https://github.com/ParisNeo/lollms-webui/assets/5471872/c946359e-a7a9-4be2-b843-3e577c9182ff)

**Comment by ParisNeo** [comment]
Please make sure you press apply settings before cobtinuing

**Comment by ParisNeo** [comment]
I'll try to change this so when someone forgets, it reminds him.

**Comment by ramzeez88** [comment]
omg , i never saw that button up there lol . thanks ParisNeo
