### ISSUE TITLE
Exception received is: No module named 'sklearn' (chat with docs)

### ISSUE THREAD

**Issue by boricuapab** [ParisNeo/lollms-webui#284]
## Expected Behavior
When selecting the chat with docs personality, it doesn't seem to install the 'sklearn' module.

## Current Behavior
Unable to properly interact with chat with docs personality

## Steps to Reproduce
Please provide detailed steps to reproduce the issue.

1. Select Chat with docs personality and save settings
2. Start a new chat
3. Upload a pdf, txt or word doc into the chat

## Possible Solution
Add the scikit-learn to the requirements.txt when installing the lollms-webui

## Context
N/A

## Screenshots
![sklearnerror2](https://github.com/ParisNeo/lollms-webui/assets/61924816/62ff36f3-0f46-472d-9969-ed4061e2c3c0)

**Comment by ParisNeo** [comment]
Oops. It is simple a missing module.
Just install scikitlearn:
pip install scikit-learn

**Comment by boricuapab** [comment]
Yep, that resolves it.
