### ISSUE TITLE
How to support _Falcon-40b-Instruct.ggmlv3.q4_0.bin_ ?

### ISSUE THREAD

**Issue by benoit-cty** [ParisNeo/lollms-webui#305]
Thanks for this tool !

How can I use it with _Falcon-40b-Instruct.ggmlv3.q4_0.bin_ ?

I can run _Falcon-40b-Instruct.ggmlv3.q4_0.bin_ locally with:
```
git clone https://github.com/jploski/ggml falcon-ggml
cd falcon-ggml
git checkout falcon40b
mkdir build && cd build && cmake .. && cmake --build . --config Release
bin/falcon -m ~/work/Falcon-40b-Instruct.ggmlv3.q4_0.bin -t 10 -n 200 -p "Hello AGI"
```

**Comment by CSnowRules** [comment]
That should be possible via CTransformers, which is currently broken. Please close this issue and refer to issue 309.

**Comment by benoit-cty** [comment]
Thanks, waiting for https://github.com/ParisNeo/lollms-webui/issues/309

**Comment by ParisNeo** [comment]
All falcon models are now supported on lollms-webui through ctransformers bindings. You can either install the models I have put in the ui or just use the url install if it is not on the zoo. Just grub the link to the .bin file from a repo like @theBloke's hugging face, paste it in url and press install.
The ctransformers binding supports loads of models. It is my favorite.

**Comment by benoit-cty** [comment]
Yes, it works, thanks ! But seems too slow for the UI : https://github.com/ParisNeo/lollms-webui/issues/310

**Comment by ParisNeo** [comment]
If you use 40B, it is  big for most gpus so many parts are handled by cpu. Use the 7B model. With gpu support that works fast.

**Comment by DarkCoverUnleashed** [comment]
How can I run this 

> All falcon models are now supported on lollms-webui through ctransformers bindings. You can either install the models I have put in the ui or just use the url install if it is not on the zoo. Just grub the link to the .bin file from a repo like @TheBloke's hugging face, paste it in url and press install. The ctransformers binding supports loads of models. It is my favorite.

Is it possible to run this model solely on CPU. I have 32gb ram but only 4GB vram

**Comment by ParisNeo** [comment]
It will be possible to run it but it may be slow. Depends on your PC

**Comment by ParisNeo** [comment]
Yes you can. All falcon models are in the models zoo. You can use the C transformers binding, it is the best for CPU on linux, windows and .
![image](https://github.com/ParisNeo/lollms-webui/assets/827993/7fe2f02d-c4e9-4dcf-94c5-f5a470d1b85c)
