### ISSUE TITLE
Model Path does not exist, when it does.. falcon-40b-ggml

### ISSUE THREAD

**Issue by linuxmagic-mp** [ParisNeo/lollms-webui#318]
Operating System: Ubuntu 20.04.6 LTS
            Kernel: Linux 5.4.0-146-generic
      Architecture: x86-64

 configs/local_config.yaml,shows 
...
binding_name: llama_cpp_official
...
model_name: falcon-40b-ggml.reference

Manually editted /lollms_data/models/llama_cpp_official/falcon-40b-ggml.reference
Tried both the full path to the quantized bin, as well as just the directory path..
```
Couldn't load model. Please verify your configuration file at /lollms_data/configs or use the next menu to select a valid model
Binding returned this exception : Model path does not exist: /models/falcon-40b-ggml/ggml-model-qt_k_m.bin

Couldn't load model. Please verify your configuration file at /lollms_data/configs or use the next menu to select a valid model
Binding returned this exception : Model path does not exist: /models/falcon-40b-ggml/
```
I

**Comment by ParisNeo** [comment]
something is odd! Are you sure  your path starts with /models/falcon-40b-ggml/ggml-model-qt_k_m.bin ?
Do you put your models directly in the root path?
if So, is the folder owned by you?
I never had such issue before.

**Comment by linuxmagic-mp** [comment]
Yeah, it is really srtrange.. walking through the debuggin now, and it is acutally in ~/models just clipped the full path .. Simple little test of os.path.exists works.. but it maybe because it is a PosixPath, and not a text string... Thew a couple of debug strings, just to make sure it was actually failing on path (line 281 in llama_cpp/llama.py)

**Comment by linuxmagic-mp** [comment]
if os.path.exists('/models/falcon-40b-ggml/ggml-model-qt_k_m.bin'): works fine and when I print str(modal_path) it looks identical, even recopied the string a couple times to make sure no hidden characters or nulls in the string. (debug same location as where it fails) So ruled out permissions, has to be somthing with how the string is passed I am guessing.. but printerd the type(model_path) and got <class 'str'> so I doubt it is that.

**Comment by linuxmagic-mp** [comment]
I did a character count, and it seem right.. but then I tried to do a simple print statement and found somthing.. 
```
print (str(model_path) + ' DEBUG')
l/models/falcon-40b-ggml/ggml-model-qt_k_m.bin
 DEBUG
```
Note the trailing characters? Now to trace it back farther.. already looked to see if it is as simple as an extra line in the reference file, but no.. However, I did a raw 'echo' of the path to the reference file, and then it worked.. Hmmmm.. (Not that many people should be editing the reference file by hand, but maybe an earlier string validation might have caught it.. but )  We can mark this solved, but good to keep on record.. For the next dummy like me.. ;)

But next thing ..
```
llama.cpp: loading model from /home/michael/models/falcon-40b-ggml/ggml-model-qt_k_m.bin
error loading model: unknown (magic, version) combination: 67676363, 0000000a; is this really a GGML file?
llama_load_model_from_file: failed to load model
```
Was wondering if everything was up to date enough for it (llama-cpp) to recognize a q4_k file, as per falcon.cpp created files.

**Comment by linuxmagic-mp** [comment]
@ParisNeo llama_cpp_python vs llama_cpp? It's a bit confusing, but isn't llama_cpp_python more actively being developed?

**Comment by ParisNeo** [comment]
They are different but both support ggml v3 llama models. The pyllamacpp is simple and small. Good if you want to use cpu and not care about options. Llama-cpp-python is a bigger project and can use gpu with offloading options. As i said before, the aim of lollms is to give a unique interface to talk to all models using any available binding out there. You havd the choice. If you have a mac, go for gpt4all binding. If you need more options and support go with ctransformers. If you want a powerful fast no latency on gpu, use gptq. You can choose what you want.

**Comment by ParisNeo** [comment]
> I did a character count, and it seem right.. but then I tried to do a simple print statement and found somthing..
> 
> ```
> print (str(model_path) + ' DEBUG')
> l/models/falcon-40b-ggml/ggml-model-qt_k_m.bin
>  DEBUG
> ```
> 
> Note the trailing characters? Now to trace it back farther.. already looked to see if it is as simple as an extra line in the reference file, but no.. However, I did a raw 'echo' of the path to the reference file, and then it worked.. Hmmmm.. (Not that many people should be editing the reference file by hand, but maybe an earlier string validation might have caught it.. but ) We can mark this solved, but good to keep on record.. For the next dummy like me.. ;)
> 
> But next thing ..
> 
> ```
> llama.cpp: loading model from /home/michael/models/falcon-40b-ggml/ggml-model-qt_k_m.bin
> error loading model: unknown (magic, version) combination: 67676363, 0000000a; is this really a GGML file?
> llama_load_model_from_file: failed to load model
> ```
> 
> Was wondering if everything was up to date enough for it (llama-cpp) to recognize a q4_k file, as per falcon.cpp created files.

Falcon is only supported by the ctransformers binding as of today. I think you can also try gptq. Just need to download a gptq version of the model. But you would need to bave enough vram as this one uses too much vram.

**Comment by linuxmagic-mp** [comment]
For the record, ctransformers recently decided to include the CUDA 12 binaries, to make it easy to run ctransformers..   Works well enoguh.. and suppports Falcon-40b-ggml, and Falcon-40b-ggml-qt_k_m quantized models..

Took less than 2mins for loading and inference.. with gpu_layers=50, stayed nicely under the limits.. 

```
nvidia-smi
Fri Jul 21 11:19:34 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.54.03              Driver Version: 535.54.03    CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4090        On  | 00000000:41:00.0  On |                  Off |
| 32%   44C    P2             128W / 450W |  20943MiB / 24564MiB |     14%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      1242      G   /usr/lib/xorg/Xorg                           59MiB |
|    0   N/A  N/A      1873      G   /usr/lib/xorg/Xorg                           72MiB |
|    0   N/A  N/A      3558      G   ...61388985,5019009179779574076,262144       40MiB |
|    0   N/A  N/A    130059      C   python3                                   20728MiB |
+---------------------------------------------------------------------------------------+
```

**Comment by linuxmagic-mp** [comment]
Original issue solved, moving on to other issues with Falcon 40b loading.
