### ISSUE TITLE
localhost:9600 -- connection refused

### ISSUE THREAD

**Issue by JackBekket** [ParisNeo/lollms-webui#327]
## Expected Behavior
Please describe the behavior you are expecting.
Launch UI
## Current Behavior
Please describe the behavior you are currently experiencing.

Launch via webui.sh and go to http://localhost:9600 in firefox browser
localhost:9600 -- connection refused (503)

## Steps to Reproduce
Please provide detailed steps to reproduce the issue.

install via webui.sh
launch via webui.sh

## Possible Solution
If you have any suggestions on how to fix the issue, please describe them here.

## Context
Ubuntu 22.02

## Screenshots
If applicable, add screenshots to help explain the issue.

**Comment by ParisNeo** [comment]
hi, did the console say that the server is serving at http://localhost:9600 ?

**Comment by JackBekket** [comment]
Hi, everything is good, I've just noticed that I forgot to turn off vpn when I've tried to dial up localhost
