### ISSUE TITLE
Something break in last update?

### ISSUE THREAD

**Issue by linuxmagic-mp** [ParisNeo/lollms-webui#329]
```
Traceback (most recent call last):
  File "~/git/lollms-webui/app.py", line 1668, in <module>
    user_avatar_path = lollms_paths.personal_user_infos_path / "default_user.svg"
AttributeError: 'LollmsPaths' object has no attribute 'personal_user_infos_path'. Did you mean: 'personal_uploads_path'?
```
Worked before as you know, rebuilt repo from scratch, and still have this error.

**Comment by linuxmagic-mp** [comment]
Problem still exists in latest pull, hoever editing as 'suggested' allows it to work.  

For the record, while I commend your work to make this project 'stupid proof', it does make the assumption that the user running the app.py is allowed to install python.  In the environment I am working, all users need to have the same environment.  There should be some form of flag that allows it to run, and simply error out if the correct python package is not installed, so the user can escalate it to the admin. 

It can lead to a user mismatch, for other python programs.

**Comment by ParisNeo** [comment]
Nope, it seems you did not update lollms library. The new library has added thjis new path. It allows adding user information like avatar, name description etc.

**Comment by linuxmagic-mp** [comment]
ctransformers                0.2.14

**Comment by linuxmagic-mp** [comment]
Sorry, wrong thread, have the latest git pull, didnt' think about the python package...
Successfully installed lollms-2.1.54

**Comment by linuxmagic-mp** [comment]
Probably should have a check to see if the correct library is in place ;)
