### ISSUE TITLE
Flask Serving JS Files with wrong mime, causes UI to fail in newer browser

### ISSUE THREAD

**Issue by Fransferdy** [ParisNeo/lollms-webui#343]
## Expected Behavior
UI Loads

## Current Behavior
UI does not load.

## Steps to Reproduce

1. run web_ui.bat
2. open crhome/edge/brave at url : http://localhost:9600/
3.  Verify it fails to load with error logged on console: 
"[Error: "Failed to load module script. Strict MIME type checking is enforced". Works on production, not on the local server](https://stackoverflow.com/questions/59355194/python-flask-error-failed-to-load-module-script-strict-mime-type-checking-i)"

## Solution
Add 
```
import mimetypes
mimetypes.add_type('application/javascript', '.js')
mimetypes.add_type('text/css', '.css')
```
 to line 57 of app.py (before flask import)

## Context
SO Windows 10, tested with Edge and Brave

**Comment by ParisNeo** [comment]
THNX.
Added to app.py
