### ISSUE TITLE
UnboundLocalError: local variable 'tokens' referenced before assignment

### ISSUE THREAD

**Issue by sunkwolf** [ParisNeo/lollms-webui#356]
## Expected Behavior
cant load a model

## Current Behavior
when i choise exllama and airoboros-l2-7B-gpt4-2.0-GPTQ already try it whit other llms to, i get an error 

## Steps to Reproduce
Please provide detailed steps to reproduce the issue.

1. launch win_run.bat
2. select discussions
3. send any msj

## Possible Solution
i dont have idea

## Context
this happens whit all the LLMS i tryied 
![Captura de pantalla 2023-08-26 095735](https://github.com/ParisNeo/lollms-webui/assets/9766451/4074c9fc-c5af-42dc-b0b8-86e7c0f6702f)

**Comment by msilich** [comment]
Same on Linux

**Comment by ParisNeo** [comment]
This was a bug I made without noticing. Fortunately I found out the problem and why it works for me and not for you.
In fact I always have debug=true in my environment, and there was a line of code that builds the tokens. I didn't pay attention and put it inside the if debug statement resulting in every thing working for me but not for those who have the debug=false option.


I have fixed this problem in the new v6.0 beta version. Just update it and you should be OK.


Again, sorry for this error. I was coding at 4 am and sleep depravation makes me miss some things.

Best regards

**Comment by msilich** [comment]
Hello, thank you for the quick bug fix. I've checked it and can confirm that the issues described in this ticket have been resolved, at least from my perspective.

**Comment by sunkwolf** [comment]
Hi, thx it just fix it for me too ;)

**Comment by sunkwolf** [comment]
thx for you fast answer, thats awesome
