### ISSUE TITLE
No module named 'petals'

### ISSUE THREAD

**Issue by superuben** [ParisNeo/lollms-webui#390]
==> started with lollms_v6_cpu.exe

==> 3 x permisson error when creating shortcuts to the desktop

==> then this from the console:

Bindings zoo found in your personal space.
Pulling last personalities zoo
fatal: not a git repository (or any of the parent directories): .git
Personalities zoo found in your personal space.
Pulling last personalities zoo
fatal: not a git repository (or any of the parent directories): .git
Extensions zoo found in your personal space.
Pulling last Extensions zoo
fatal: not a git repository (or any of the parent directories): .git
Qlora found in your personal space.
Pulling last qlora code
fatal: cannot change to 'D:\LoLLMs_webUI\lollms-webui\personal_data\trainers\gptqlora': No such file or directory
>Loading binding c_transformers. Please wait ...
Binding c_transformers loaded successfully.
No model selected
Personality  lollms mounted successfully but no model is selected
Checking discussions database... ok
Your personal data is stored here :D:\LoLLMs_webUI\lollms-webui\personal_data
Checking for updates from D:\LoLLMs_webUI\lollms-webui
debug mode:false
Please open your browser and go to http://localhost:9600 to view the ui
 * Serving Flask app 'Lollms-WebUI'
 * Debug mode: off
Client ipx-imaGk-pEEEqSAAAB connected
Lollms webui version : 6.5
Listing models

==> webserver up and running, trying binding zoo to install petals
then we get the uvloop error, but the installation reports as installed
it reports that a model is loaded

Collecting uvloop>=0.14.0 (from hivemind==1.1.10.post2->petals==2.2.0)
  Using cached uvloop-0.17.0.tar.gz (2.3 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "D:\LoLLMs_webUI\installer_files\temp\pip-install-lwib385_\uvloop_44a06195732f4378a440654d16dec5da\setup.py", line 8, in <module>
          raise RuntimeError('uvloop does not support Windows at the moment')
      RuntimeError: uvloop does not support Windows at the moment
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Installed successfully
Model loaded successfully
Configuration binding_name updated
Requested updating of setting model_name to None
Trying to set a None model. Please select a model for the binding
update_settings : New model selected
Configuration model_name updated
Listing models
Models:
[{'category': 'generic', 'datasets': 'unknown', 'icon': '', 'last_commit_time': datetime.datetime(2023, 9, 17, 17, 21, 17, tzinfo=datetime.timezone.utc), 'license': 'llama2', 'model_creator': 'bigscience', 'model_creator_link': 'https://huggingface.co/bigscience', 'name': 'petals-team/StableBeluga2', 'quantizer': 'None', 'rank': 10000000000.0, 'type': 'gptq', 'model_type': 'api', 'variants': [{'name': 'StableBeluga2', 'size': 35332203544}]}]

==> then i goto http://localhost:9600/settings/ to apply changes
configuration saved successfully

==> then i goto the models tab to select petals with stable beluga
it tries to load it, but fails and in the command prompt i see this:

OK
 ╔══════════════════════════════════════════════════╗
 ║           Building mounted Personalities         ║
 ╚══════════════════════════════════════════════════╝
* generic/lollms
selected : 0
 ╔══════════════════════════════════════════════════╗
 ║                      Done                        ║
 ╚══════════════════════════════════════════════════╝
Requested updating of setting model_name to petals-team/StableBeluga2
Couldn't load model: [No module named 'petals']
Traceback (most recent call last):
  File "D:\LoLLMs_webUI\lollms-webui\app.py", line 793, in update_setting
    self.model = self.binding.build_model()
  File "D:\LoLLMs_webUI\lollms-webui\personal_data\bindings_zoo\bs_petals\__init__.py", line 120, in build_model
    from petals import AutoDistributedModelForCausalLM
ModuleNotFoundError: No module named 'petals'

==> trying to restart backend, maybe then it picks up on what it installed?
==> trying to start a discussion, doesnt work, says i need to select a model
==> Model changed to petals-team/StableBeluga2 (frontend)
==> typing a message in a new discussion
Model not selected. Please select a model (webui)

Requested updating of setting model_name to petals-team/StableBeluga2
Couldn't load model: [No module named 'petals']
Traceback (most recent call last):
  File "D:\LoLLMs_webUI\lollms-webui\app.py", line 793, in update_setting
    self.model = self.binding.build_model()
  File "D:\LoLLMs_webUI\lollms-webui\personal_data\bindings_zoo\bs_petals\__init__.py", line 120, in build_model
    from petals import AutoDistributedModelForCausalLM
ModuleNotFoundError: No module named 'petals'

==> (that was from the console/command prompt)
lets try to update the backend from the webui

 ╔══════════════════════════════════════════════════╗
 ║                Updating backend                  ║
 ╚══════════════════════════════════════════════════╝

Traceback (most recent call last):
  File "D:\LoLLMs_webUI\lollms-webui\update_script.py", line 48, in <module>
    main()
  File "D:\LoLLMs_webUI\lollms-webui\update_script.py", line 30, in main
    run_git_pull()
  File "D:\LoLLMs_webUI\lollms-webui\update_script.py", line 10, in run_git_pull
    repo = git.Repo(".")
  File "D:\LoLLMs_webUI\installer_files\lollms_env\lib\site-packages\git\repo\base.py", line 266, in __init__
    raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: D:\LoLLMs_webUI\lollms-webui

==> trying to reinstall petals bindings from binding zoo, doesnt work
end result: model not loaded

== a few days ago, i tried to use a user input field to search something, and 90% of the body blanked out. so many bugs (for me)

**Comment by ParisNeo** [comment]
Hi, if you want to install petals you need to use the petals installer it is the other exe.
petals uses uvloop which is a library that doesn't support windows :(

So the only way is to use the special installer. It installs ubuntu on windows through WSL then you can run petals.
Best regards
