### ISSUE TITLE
Problems with AllGPT binding

### ISSUE THREAD

**Issue by ediweber** [ParisNeo/lollms-webui#430]
## Expected Behavior
A GGUF Model could be loaded vie AllGPT binding

## Current Behavior

Hello.

First things first: Thank you for creating lollms, it is simply spoken wonderful!

Unfortunately I suffer with the AllGPT binding. I cannot load my GGUF models, output is:

Lollms webui version : 6.8
Listing all extensions
Listing all personalities
Listing models
Loading discussion for client mrQYbMGCR0JO3rJSAAAB
Checking for updates from E:\lollms-webui
update availability: True
Listing all extensions

    Retreiving binding settings
    Requested updating of setting model_name to Naberius-7B-GGUF
    Changing model to: Naberius-7B-GGUF
    Loading model:naberius-7b.Q8_0.gguf
    Folder:E:\loldata\models\gguf
    Error allocating memory ErrorOutOfDeviceMemory
    error loading model: Error allocating vulkan memory.
    llama_load_model_from_file: failed to load model
    LLAMA ERROR: failed to load model from E:\\loldata\\models\\gguf\naberius-7b.Q8_0.gguf
    Couldn't load model: [Model not loaded]
    Traceback (most recent call last):
    File "E:\lollms-webui\app.py", line 914, in update_setting
    self.model = self.binding.build_model()
    File "E:\lollms-webui\zoos\bindings_zoo\gpt_4all_init_.py", line 120, in build_model
    self.model.model.set_thread_count(self.binding_config.n_threads)
    File "C:\Users\eduar\anaconda3\envs\lol\lib\site-packages\gpt4all\pyllmodel.py", line 274, in set_thread_count
    raise Exception("Model not loaded")
    Exception: Model not loaded

I suspect that it tries to use my APU (Ryzen 5600) @ 4GB instead of my Nvidia 3060 - 12 GB, is there a simple way to force it to use the Nvidia card.

Will try with smaller models. In fact it would be nice to have a small one running on the APU and a large one on the dedicated GPU card.

## Possible Solution

I tried a workaround with setting the env var CUDA_VISIBLE_DEVICES=1 and then starting app.py
However the api still gives the same error. Fun fact: after setting CUDA_VISIBLE_DEVICES my resource monitor shows, that AllGPT binding at least tries to allocate memory... 

As a last resort I disabled AMD GPU in bios, but still the same behavior.

When loading into koboldcpp everything works fine with all configs. Maybe you can add a koboldcpp binding? or an openAI binding where I can specify my local openAI server ip?

## Context
win11, ryzen 5600g, nvidia 3060
loading with cpu works fine but is of course slow.

## Screenshots
If applicable, add screenshots to help explain the issue.

**Comment by ediweber** [comment]
Okay... sooo sorry... I finally found a very easy fix for all of my problems:

I am now using: 

Binding: c_transformers

works perfectly with

Model: Naberius-7B-GGUF

I can even select how many layers to offload to the GPU. Now I have everything I wanted. (I guess I got confused because exllama is your fav for GPU and c_trans for CPU ;-) Sorry for all those raised issues.

Even the "disappearing prompt" issue seems to be solved for me. It's plain simple. If no model is working, no prompt will appear, which seems quite logical now.
 
I am very eager now to test the personality creator, thank you sooooo much for this extraordinary piece of software which (besides its growing pains (mainly due to rapid development in this area) is extremely well thought of. I really like the architecture. You have done a great job. I hope to dig deeper into the details of lollms_personality_maker, as it seems the perfect fit for my purposes. It is exactly what I tried to implement myself before, but with this at hand... you are simply gorgeos!!!

Please close my issues. I had a bad software day ;-)

**Comment by ediweber** [comment]
I just found out that I can close an issue. (I am github member since 2008 and never raised anything ;-) outch.

**Comment by ParisNeo** [comment]
Hi. Sorry for that. It is my mistake. GPT4ALL only support Q4.0 I should change the zoo accordingly.
