### ISSUE TITLE
Problems with AutoAWQ binding

### ISSUE THREAD

**Issue by ediweber** [ParisNeo/lollms-webui#431]
## Expected Behavior
Load awq models

## Current Behavior
Requested updating of setting model_name to Naberius-7B-AWQ
Changing model to: Naberius-7B-AWQ
*-*-*-*-*-*-*-*
Cuda VRAM usage
*-*-*-*-*-*-*-*
{'nb_gpus': 1, 'gpu_0_total_vram': 12884901888, 'gpu_0_used_vram': 704643072, 'gpu_0_model': 'NVIDIA GeForce RTX 3060'}
Cleared cache
*-*-*-*-*-*-*-*
Cuda VRAM usage
*-*-*-*-*-*-*-*
{'nb_gpus': 1, 'gpu_0_total_vram': 12884901888, 'gpu_0_used_vram': 704643072, 'gpu_0_model': 'NVIDIA GeForce RTX 3060'}
Creating tokenizer E:\loldata\models\awq\Naberius-7B-AWQ
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
ok
Creating model E:\loldata\models\awq\Naberius-7B-AWQ
Using device map: cuda:0
Couldn't load model: [Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory E:\loldata\models\awq\Naberius-7B-AWQ.]

## Possible Solution
autoAWQ expects a pytorch_model.bin but a .safetensors file is presented. As the .safetensors format becomes more common it would be greatly appreciated if autoAWQ would accept this format.

## Context
Cannot get allGPT binding to run on my Nvidia3060, exlama2 also not working properly, so I tried with AutoAWG...

...wish me luck ;-)
(it is quite frustrating, to see such a great ui as lollms-webui with EXACTLY what I wished for, and then suffering to get any model running ;-) used koboldcpp and textgen-webui and allGPT (standalone) and every one worked quite well but didn't fit my needs. Now I have finally found lollms-webui which is really great (from what I can test with running Naberius on my CPU...) I really love it, but I can't find a way to get any of my models running on GPU nor can I manage to access a local run API... 

Next step will be to try writing my own binding for a locally run kobold_cpp.API as that would solve all my problems. wish me luck, I am tired and not that good in python ;-)
sorry for so much off-topic ;-)

**Comment by ediweber** [comment]
Okay... sooo sorry... I finally found a very easy fix for all of my problems:

I am now using:

Binding: c_transformers

works perfectly with

Model: Naberius-7B-GGUF

I can even select how many layers to offload to the GPU. Now I have everything I wanted. Sorry for all those raised issues.

**Comment by ParisNeo** [comment]
AWQ binding is under repair. Sorry
