### ISSUE TITLE
Discussion tab missing input functionality after update

### ISSUE THREAD

**Issue by genewitch** [ParisNeo/lollms-webui#442]
## Expected Behavior
In discussion tab, the ability to input text and submit it; it was working last night,

## Current Behavior
 this morning it updated and that part of the webui is *gone*

## Steps to Reproduce
Closed the cmd.exe window last night when i was done.
ran win_run.bat in the main folder "d:\opt\lollms\win_run.bat"
It updated two things, one of which was lollms-webui 
discussion page comes up, the discussions are all there, but no way to interact

## Possible Solution
roll back to whatever i was using last night, but i rebooted my PC to free up VRAM so i have no idea what the blob id was!

## Context
I don't know how to roll back to whatever i was using last night. ANd i *had* turned off automatic updates, but i guess that got reset?

## Screenshots
![image](https://github.com/ParisNeo/lollms-webui/assets/3182020/b3090abd-28ad-439c-a32a-bd882650e142)

**Comment by genewitch** [comment]
I forced an update in the settings tab and it seems to have been fixed. I rebooted twice and started it up again twice, and it said "Update Available: True" but never updated again.

It looks like it uninstalls numpy 1.26.X and 1.24.X and then reinstalls 1.26.X again. Sorry for spamming the list!

**Comment by ParisNeo** [comment]
Hi. Many updates require reboot of the app unfortunately.
