### ISSUE TITLE
Unable to run on Ubuntu 23

### ISSUE THREAD

**Issue by apstrom** [ParisNeo/lollms-webui#459]
## Expected Behavior
Run `python app.py`

## Current Behavior
I have used the installer script to install LOLLMS. When I enter the conda environment and run 
`python app.py`.

The app runs; returns this error:

Traceback (most recent call last):
  File "/home/adam/lollms/lollms-webui/app.py", line 70, in <module>
    from api.db import Discussion
  File "/home/adam/lollms/lollms-webui/api/__init__.py", line 23, in <module>
    from lollms.media import WebcamImageSender, AudioRecorder
  File "/home/adam/lollms/lollms-webui/lollms_core/lollms/media.py", line 18, in <module>
    import cv2
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

## Steps to Reproduce
Appears to be system-specific.

1. Install using installer script or miniconda3.
2. Enter conda environment.
3. Change directory to app.py location.
4. Run `python app.py`

## Possible Solution
I'm puzzled--admittedly not a great coder. Excellent end-user, though. 

## Context
Fresh install of Ubuntu 23. Same issue on Debian 11. 
Running the installation in PVE container.

## Screenshots
N/A

**Comment by NeoPlayer13** [comment]
Same problem! Running in a VM with a fresh lunar-server-cloudimg-amd64-disk-kvm.img.

**Comment by apstrom** [comment]
I have also now tested a fresh Ubuntu 23 container using linux_run.sh. Same error.

**Comment by JImRock33** [comment]
i jystr followed the new instructions...uo and running  !!!!! just authorizze ur location when asked to.  thank you Neo !

**Comment by apstrom** [comment]
> i jystr followed the new instructions...uo and running !!!!! just authorizze ur location when asked to. thank you Neo !

Where are these instructions?

**Comment by JImRock33** [comment]
the main page just changed 20 min utes ago

**Comment by JImRock33** [comment]
st authorize git to use the repo: Lollms_core found in the app space.
Pulling last lollms_core
fatal: detected dubious ownership in repository at '/mnt/1F70BDBD2D31C071/lollms-webui/lollms_core'
To add an exception for this directory, call:

	git config --global --add safe.directory /mnt/1F70BDBD2D31C071/lollms-webui/lollms_core
safe_store_path found in the app space.
Pulling last safe_store_path
fatal: detected dubious ownership in repository at '/mnt/1F70BDBD2D31C071/lollms-webui/utilities/safe_store'
To add an exception for this directory, call:

	git config --global --add safe.directory /mnt/1F70BDBD2D31C071/lollms-webui/utilities/safe_store
Bindings zoo found in your personal space.
Pulling last personalities zoo
fatal: detected dubious ownership in repository at '/mnt/1F70BDBD2D31C071/lollms-webui/zoos/bindings_zoo'
To add an exception for this directory, call:

	git config --global --add safe.directory /mnt/1F70BDBD2D31C071/lollms-webui/zoos/bindings_zoo
Personalities zoo found in your personal space.
Pulling last personalities zoo
fatal: detected dubious ownership in repository at '/mnt/1F70BDBD2D31C071/lollms-webui/zoos/personalities_zoo'
To add an exception for this directory, call:

	git config --global --add safe.directory /mnt/1F70BDBD2D31C071/lollms-webui/zoos/personalities_zoo
Extensions zoo found in your personal space.
Pulling last Extensions zoo
fatal: detected dubious ownership in repository at '/mnt/1F70BDBD2D31C071/lollms-webui/zoos/extensions_zoo'
To add an exception for this directory, call:

	git config --global --add safe.directory /mnt/1F70BDBD2D31C071/lollms-webui/zoos/extensions_zoo
Models zoo found in your personal space.
Pulling last Models zoo
fatal: detected dubious ownership in repository at '/mnt/1F70BDBD2D31C071/lollms-webui/zoos/models_zoo'
To add an exception for this directory, call:

	git config --global --add safe.directory /mnt/1F70BDBD2D31C071/lollms-webui/zoos/models_zoo
>Loading binding remote_lollms. Please

**Comment by JImRock33** [comment]
just have a problem forcing me to reinstall env each time i add a binding cos Unable to locate package portaudio19-dev python3-pyaudio.. surelly nothing

**Comment by apstrom** [comment]
The fix that was committed worked. I get a non-fatal error regarding pyaudio on start, but that is not a problem at the moment.

**Comment by NeoPlayer13** [comment]
Tried with the Fedora cloud image. Same error! It throw off the system-specific theory.
Solved using `apt install install ffmpeg libsm6 libxext6`. It will download nvidia-cuda, numba, triton and other dependencies. But it's fully working after that.

**Comment by JImRock33** [comment]
can't relaunch in fact

> Tried with the Fedora cloud image. Same error! It throw off the system-specific theory. Solved using `apt install install ffmpeg libsm6 libxext6`. It will download nvidia-cuda, numba, triton and other dependencies. But it's fully working after that.

in the new whole wokfloaw ? or as an indempndant cmd ?  thx for u being on the topic  !!!!

**Comment by NeoPlayer13** [comment]
It's more like a workaround.

**Comment by JImRock33** [comment]
so i do i run it please ?  in the conda env ?  thx

**Comment by JImRock33** [comment]
t'es français hein ?

**Comment by JImRock33** [comment]
kifkif bourricocotte

(base) dizux@dizux-CF:/mnt/1F70BDBD2D31C071/lollms-webui$ sudo apt install ffmpeg libsm6 libxext6
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ffmpeg is already the newest version (7:6.0-6ubuntu1).
ffmpeg set to manually installed.
libsm6 is already the newest version (2:1.2.3-1build2).
libsm6 set to manually installed.
libxext6 is already the newest version (2:1.3.4-1build1).
libxext6 set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
(base) dizux@dizux-CF:/mnt/1F70BDBD2D31C071/lollms-webui$

**Comment by NeoPlayer13** [comment]
> t'es français hein ?

My native language is Spanish. It's a workaround for the original problem. `ImportError: libGL.so.1: cannot open shared object file: No such file or directory`

**Comment by JImRock33** [comment]
doesn't work, everything already up to date///

**Comment by NeoPlayer13** [comment]
Does it still returns the original error message when you run linux_run.sh? Or you got a new one?

**Comment by JImRock33** [comment]
don't use the script, doesn't work, using the condan env manuallly , just take 3 mn , ije=ust figured out that only reinstalling dependencies is enough to relaunch////
