### ISSUE TITLE
convert_language_name function missing

### ISSUE THREAD

**Issue by bourneash** [ParisNeo/lollms-webui#465]
## Expected Behavior
Launch the app.py without any errors

## Current Behavior
Unable to launch the application

## Steps to Reproduce
- pull down latest repo
- remove virtual environment and recreate
- try to run `python app.py --host 0.0.0.0`

Error:
Traceback (most recent call last):
  File "/home/user/lollms-webui/app.py", line 30, in <module>
    from lollms.utilities import AdvancedGarbageCollector, reinstall_pytorch_with_cuda, convert_language_name
ImportError: cannot import name 'convert_language_name' from 'lollms.utilities' (/home/user/lollms-webui/lollms_core/lollms/utilities.py)

## Context
If change app.py line:
from lollms.utilities import AdvancedGarbageCollector, reinstall_pytorch_with_cuda, convert_language_name
to
from lollms.utilities import AdvancedGarbageCollector, reinstall_pytorch_with_cuda #, convert_language_name
launch the app with `python app.py --host 0.0.0.0` and then remove the comment from above the app will launch again

Also, looks like there might be some work being done around this recently: https://github.com/ParisNeo/lollms-webui/blame/bb43498c89c185eab2d67af8d86a984cfdb80568/api/__init__.py#L41

**Comment by ParisNeo** [comment]
Hi, this function is in lollms_core. It has been added lately. It is in the repo, so maybe you just need to co to the folder lollms_core and do a git pull.

**Comment by bourneash** [comment]
That would be it! Thank you and happy holidays!

**Comment by ParisNeo** [comment]
You are welcome
