### ISSUE TITLE
(Solved, not implemented yet) Windows 11, exllama, cpu_mode:  positional argument errors on some personalities due to outdated generator. Please re-generate 

### ISSUE THREAD

**Issue by ba2512005** [ParisNeo/lollms-webui#480]
## Expected Behavior
Personalities should work as intended. Get's stuck in warming up on the UI screen and the server outputs error message below. 

## Current Behavior
Some personalities fail on the workflow execution. 

Workflow run failed.
Error:Processor.run_workflow() takes from 2 to 4 positional arguments but 5 were given
Traceback (most recent call last):
File "C:\Users\ba251\lollms-webui\scripts\windows\lollms-webui\lollms_webui.py", line 1262, in generate
self.personality.processor.run_workflow( prompt, full_prompt, callback, context_details)
TypeError: Processor.run_workflow() takes from 2 to 4 positional arguments but 5 were given

## Steps to Reproduce
Load lord of internet personality on windows with exllamav2 binding using cpu mode. 

## Possible Solution
Seems like there's a positional argument issue where it's expecting 2-4 arguments but 5 were given, the function declaration and the calling function are different. The generator used for creating this personality is older than the one calling it, having a mismatch of argument types. When debugging, it points to the generator instead of the generated code. after some digging I found the solution

Edit: see comments below on fix. 

## Context
Personalities that search the internet. 
Using Windows 11, CPU mode, exllama binding

## Screenshots
There is no error on the UI portion. Not sure if it's enabling it or not

**Comment by ba2512005** [comment]
Also similar error for Processor.run_workflow()

Traceback (most recent call last):
  File "C:\Users\ba251\lollms-webui\scripts\windows\lollms-webui\lollms_webui.py", line 1262, in generate
    self.personality.processor.run_workflow( prompt, full_prompt, callback, context_details)
TypeError: Processor.run_workflow() takes from 2 to 4 positional arguments but 5 were given

Workflow run failed.
Error:Processor.run_workflow() takes from 2 to 4 positional arguments but 5 were given
Traceback (most recent call last):
  File "C:\Users\ba251\lollms-webui\scripts\windows\lollms-webui\lollms_webui.py", line 1262, in generate
    self.personality.processor.run_workflow( prompt, full_prompt, callback, context_details)
TypeError: Processor.run_workflow() takes from 2 to 4 positional arguments but 5 were given

Workflow run failed
Error:Processor.run_workflow() takes from 2 to 4 positional arguments but 5 were given
--> Exception from personality:Workflow run failed
Error:Processor.run_workflow() takes from 2 to 4 positional arguments but 5 were given
Finished executing the workflow

## Done Generation ##

**Comment by ba2512005** [comment]
Additionally it seems some personalities are based on older generation code and need to be re-created and cleaned up.

I made it work by modifying the def run_workflow definition in the file: zoos/personality_zoo/internet/<personality_name>/processor.py

to:

    def run_workflow(self, prompt: str, previous_discussion_text: str = "", callback: Callable[[str, MSG_TYPE, dict, list], bool] = None, context_details: dict = None):

**Comment by ba2512005** [comment]
@ParisNeo I just looked through the code and found 3 that need to be changed:
Thinking_methodologies/tree_of_thoughts (which you already did)

Additionally:
Thinking_methodologies/chain_of_thoughts
data/database_maker
data/text2bulletpoints

**Comment by ParisNeo** [comment]
Thanks
I'll fix them now

**Comment by ParisNeo** [comment]
Well got distracted by something else and didn't do it. I'll try tomorrow if i find the Time

**Comment by ba2512005** [comment]
personalities updated
