### ISSUE TITLE
persona "Pc operator" dbug error.

### ISSUE THREAD

**Issue by ediweber** [ParisNeo/lollms-webui#490]
Hi there, I really like the idea of the pc operator persona. However I am stuck while trying to make it ruin my pc ;-)

Here is the error msg:

--> Step started:Planning operation
Traceback (most recent call last):
  File "E:\lol9\lollms-webui\zoos\personalities_zoo\control\pc_operator\scripts\processon
    plan = self.plan_with_images(prompt, [sc_path],
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\lol9\lollms-webui\lollms_core\lollms\personality.py", line 2385, in plan_withs
    gen = self.generate_with_images(prompt, images, max_answer_length).strip().replace(")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\lol9\lollms-webui\lollms_core\lollms\personality.py", line 1846, in generate_s
    return self.personality.generate_with_images(prompt, images, max_size, temperature, )
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: AIPersonality.generate_with_images() got multiple values for argument 'debug'

--> Step ended:Planning operation
Finished executing the workflow

I hope you can help. I really want pc operator to take over my PC ;-)

**Comment by ParisNeo** [comment]
Thanks for pointing out this problem.

The pc operator persona requires using GPT4-vision model. It is the only model capable of doing this (for now). Other models like llava or backllava are not yet up to the task :)

They will probably become better over time.
