### ISSUE TITLE
help me with manual installation

### ISSUE THREAD

**Issue by Fuckingnameless** [ParisNeo/lollms-webui#505]
## Expected Behavior
to run the app

## Current Behavior
```
python app.py
Traceback (most recent call last):
  File "/home/github/lollms-webui/app.py", line 12, in <module>
    from lollms.app import LollmsApplication
ModuleNotFoundError: No module named 'lollms'

`sudo python3 app.py

Traceback (most recent call last):
  File "/home/user/github/lollms-webui/app.py", line 9, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
`
```
## Steps to Reproduce
Please provide detailed steps to reproduce the issue.

```
sudo git clone https://github.com/ParisNeo/lollms-webui.git
cd lollms-webui
conda create -n env_lollms
conda activate env_lollms
   git submodule init
   git submodule update
   cd zoos/bindings_zoo
   git checkout main
   cd ../personalities_zoo
   git checkout main
   cd ../extensions_zoo
   git checkout main
   cd ../models_zoo
   git checkout main
   cd ../../lollms_core
   git checkout main
   pip install -e .
   cd ../utilities/safe_store
   git checkout main
   pip install -e .

sudo python3 app.py or python app.py

```

## Possible Solution
it may be the way i'm installing something?

## Context
i'm new to conda not sure but seems to be related to virtual environments?

install log:

`pip install -e .
Obtaining file:///home/user/github/lollms-webui
  Preparing metadata (setup.py) ... done
Requirement already satisfied: colorama in /opt/anaconda3/lib/python3.11/site-packages (from Lollms-webui==5.0.2) (0.4.6)
Requirement already satisfied: numpy==1.24.* in /opt/anaconda3/lib/python3.11/site-packages (from Lollms-webui==5.0.2) (1.24.4)
Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.11/site-packages (from Lollms-webui==5.0.2) (2.2.1)
Requirement already satisfied: Pillow>=9.5.0 in /opt/anaconda3/lib/python3.11/site-packages (from Lollms-webui==5.0.2) (10.2.0)
Requirement already satisfied: pyyaml in /opt/anaconda3/lib/python3.11/site-packages (from Lollms-webui==5.0.2) (6.0.1)
Requirement already satisfied: requests in /opt/anaconda3/lib/python3.11/site-packages (from Lollms-webui==5.0.2) (2.31.0)
Requirement already satisfied: rich in /opt/anaconda3/lib/python3.11/site-packages (from Lollms-webui==5.0.2) (13.7.1)
Requirement already satisfied: scipy in /opt/anaconda3/lib/python3.11/site-packages (from Lollms-webui==5.0.2) (1.12.0)
Requirement already satisfied: tqdm in /opt/anaconda3/lib/python3.11/site-packages (from Lollms-webui==5.0.2) (4.66.2)
Requirement already satisfied: setuptools in /opt/anaconda3/lib/python3.11/site-packages (from Lollms-webui==5.0.2) (69.1.1)
Requirement already satisfied: psutil in /opt/anaconda3/lib/python3.11/site-packages (from Lollms-webui==5.0.2) (5.9.8)
Requirement already satisfied: pytest in /opt/anaconda3/lib/python3.11/site-packages (from Lollms-webui==5.0.2) (8.0.2)
Requirement already satisfied: GitPython in /opt/anaconda3/lib/python3.11/site-packages (from Lollms-webui==5.0.2) (3.1.42)
Requirement already satisfied: ascii_colors>=0.1.4 in /opt/anaconda3/lib/python3.11/site-packages (from Lollms-webui==5.0.2) (0.2.2)
Requirement already satisfied: beautifulsoup4 in /opt/anaconda3/lib/python3.11/site-packages (from Lollms-webui==5.0.2) (4.12.3)
Requirement already satisfied: packaging in /opt/anaconda3/lib/python3.11/site-packages (from Lollms-webui==5.0.2) (23.2)
Requirement already satisfied: fastapi in /opt/anaconda3/lib/python3.11/site-packages (from Lollms-webui==5.0.2) (0.110.0)
Requirement already satisfied: uvicorn in /opt/anaconda3/lib/python3.11/site-packages (from Lollms-webui==5.0.2) (0.27.1)
Requirement already satisfied: python-multipart in /opt/anaconda3/lib/python3.11/site-packages (from Lollms-webui==5.0.2) (0.0.9)
Requirement already satisfied: python-socketio in /opt/anaconda3/lib/python3.11/site-packages (from Lollms-webui==5.0.2) (5.11.1)
Requirement already satisfied: pydantic in /opt/anaconda3/lib/python3.11/site-packages (from Lollms-webui==5.0.2) (2.6.3)
Requirement already satisfied: selenium in /opt/anaconda3/lib/python3.11/site-packages (from Lollms-webui==5.0.2) (4.18.1)
Requirement already satisfied: tiktoken in /opt/anaconda3/lib/python3.11/site-packages (from Lollms-webui==5.0.2) (0.6.0)
Requirement already satisfied: soupsieve>1.2 in /opt/anaconda3/lib/python3.11/site-packages (from beautifulsoup4->Lollms-webui==5.0.2) (2.5)
Requirement already satisfied: starlette<0.37.0,>=0.36.3 in /opt/anaconda3/lib/python3.11/site-packages (from fastapi->Lollms-webui==5.0.2) (0.36.3)
Requirement already satisfied: typing-extensions>=4.8.0 in /opt/anaconda3/lib/python3.11/site-packages (from fastapi->Lollms-webui==5.0.2) (4.9.0)
Requirement already satisfied: annotated-types>=0.4.0 in /opt/anaconda3/lib/python3.11/site-packages (from pydantic->Lollms-webui==5.0.2) (0.6.0)
Requirement already satisfied: pydantic-core==2.16.3 in /opt/anaconda3/lib/python3.11/site-packages (from pydantic->Lollms-webui==5.0.2) (2.16.3)
Requirement already satisfied: gitdb<5,>=4.0.1 in /opt/anaconda3/lib/python3.11/site-packages (from GitPython->Lollms-webui==5.0.2) (4.0.7)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.11/site-packages (from pandas->Lollms-webui==5.0.2) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.11/site-packages (from pandas->Lollms-webui==5.0.2) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.11/site-packages (from pandas->Lollms-webui==5.0.2) (2023.3)
Requirement already satisfied: iniconfig in /opt/anaconda3/lib/python3.11/site-packages (from pytest->Lollms-webui==5.0.2) (1.1.1)
Requirement already satisfied: pluggy<2.0,>=1.3.0 in /opt/anaconda3/lib/python3.11/site-packages (from pytest->Lollms-webui==5.0.2) (1.4.0)
Requirement already satisfied: bidict>=0.21.0 in /opt/anaconda3/lib/python3.11/site-packages (from python-socketio->Lollms-webui==5.0.2) (0.23.1)
Requirement already satisfied: python-engineio>=4.8.0 in /opt/anaconda3/lib/python3.11/site-packages (from python-socketio->Lollms-webui==5.0.2) (4.9.0)
Requirement already satisfied: aiohttp>=3.4 in /opt/anaconda3/lib/python3.11/site-packages (from python-socketio[asyncio_client]->Lollms-webui==5.0.2) (3.9.3)
Requirement already satisfied: websocket-client>=0.54.0 in /opt/anaconda3/lib/python3.11/site-packages (from python-socketio[client]->Lollms-webui==5.0.2) (0.58.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/lib/python3.11/site-packages (from requests->Lollms-webui==5.0.2) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.11/site-packages (from requests->Lollms-webui==5.0.2) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.11/site-packages (from requests->Lollms-webui==5.0.2) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.11/site-packages (from requests->Lollms-webui==5.0.2) (2024.2.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /opt/anaconda3/lib/python3.11/site-packages (from rich->Lollms-webui==5.0.2) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/anaconda3/lib/python3.11/site-packages (from rich->Lollms-webui==5.0.2) (2.15.1)
Requirement already satisfied: trio~=0.17 in /opt/anaconda3/lib/python3.11/site-packages (from selenium->Lollms-webui==5.0.2) (0.24.0)
Requirement already satisfied: trio-websocket~=0.9 in /opt/anaconda3/lib/python3.11/site-packages (from selenium->Lollms-webui==5.0.2) (0.11.1)
Requirement already satisfied: regex>=2022.1.18 in /opt/anaconda3/lib/python3.11/site-packages (from tiktoken->Lollms-webui==5.0.2) (2023.10.3)
Requirement already satisfied: click>=7.0 in /opt/anaconda3/lib/python3.11/site-packages (from uvicorn->Lollms-webui==5.0.2) (8.1.7)
Requirement already satisfied: h11>=0.8 in /opt/anaconda3/lib/python3.11/site-packages (from uvicorn->Lollms-webui==5.0.2) (0.14.0)
Requirement already satisfied: aiosignal>=1.1.2 in /opt/anaconda3/lib/python3.11/site-packages (from aiohttp>=3.4->python-socketio[asyncio_client]->Lollms-webui==5.0.2) (1.2.0)
Requirement already satisfied: attrs>=17.3.0 in /opt/anaconda3/lib/python3.11/site-packages (from aiohttp>=3.4->python-socketio[asyncio_client]->Lollms-webui==5.0.2) (23.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /opt/anaconda3/lib/python3.11/site-packages (from aiohttp>=3.4->python-socketio[asyncio_client]->Lollms-webui==5.0.2) (1.4.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /opt/anaconda3/lib/python3.11/site-packages (from aiohttp>=3.4->python-socketio[asyncio_client]->Lollms-webui==5.0.2) (6.0.4)
Requirement already satisfied: yarl<2.0,>=1.0 in /opt/anaconda3/lib/python3.11/site-packages (from aiohttp>=3.4->python-socketio[asyncio_client]->Lollms-webui==5.0.2) (1.9.3)
Requirement already satisfied: smmap<5,>=3.0.1 in /opt/anaconda3/lib/python3.11/site-packages (from gitdb<5,>=4.0.1->GitPython->Lollms-webui==5.0.2) (4.0.0)
Requirement already satisfied: mdurl~=0.1 in /opt/anaconda3/lib/python3.11/site-packages (from markdown-it-py>=2.2.0->rich->Lollms-webui==5.0.2) (0.1.0)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas->Lollms-webui==5.0.2) (1.16.0)
Requirement already satisfied: simple-websocket>=0.10.0 in /opt/anaconda3/lib/python3.11/site-packages (from python-engineio>=4.8.0->python-socketio->Lollms-webui==5.0.2) (1.0.0)
Requirement already satisfied: anyio<5,>=3.4.0 in /opt/anaconda3/lib/python3.11/site-packages (from starlette<0.37.0,>=0.36.3->fastapi->Lollms-webui==5.0.2) (4.2.0)
Requirement already satisfied: sortedcontainers in /opt/anaconda3/lib/python3.11/site-packages (from trio~=0.17->selenium->Lollms-webui==5.0.2) (2.4.0)
Requirement already satisfied: outcome in /opt/anaconda3/lib/python3.11/site-packages (from trio~=0.17->selenium->Lollms-webui==5.0.2) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in /opt/anaconda3/lib/python3.11/site-packages (from trio~=0.17->selenium->Lollms-webui==5.0.2) (1.3.0)
Requirement already satisfied: wsproto>=0.14 in /opt/anaconda3/lib/python3.11/site-packages (from trio-websocket~=0.9->selenium->Lollms-webui==5.0.2) (1.2.0)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in /opt/anaconda3/lib/python3.11/site-packages (from urllib3[socks]<3,>=1.26->selenium->Lollms-webui==5.0.2) (1.7.1)
Installing collected packages: Lollms-webui
  Running setup.py develop for Lollms-webui
    error: subprocess-exited-with-error
    
    × python setup.py develop did not run successfully.
    │ exit code: 1
    ╰─> [30 lines of output]
        running develop
        /opt/anaconda3/lib/python3.11/site-packages/setuptools/command/develop.py:40: EasyInstallDeprecationWarning: easy_install command is deprecated.
        !!
        
                ********************************************************************************
                Please avoid running ``setup.py`` and ``easy_install``.
                Instead, use pypa/build, pypa/installer or other
                standards-based tools.
        
                See https://github.com/pypa/setuptools/issues/917 for details.
                ********************************************************************************
        
        !!
          easy_install.initialize_options(self)
        /opt/anaconda3/lib/python3.11/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
        !!
        
                ********************************************************************************
                Please avoid running ``setup.py`` directly.
                Instead, use pypa/build, pypa/installer or other
                standards-based tools.
        
                See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
                ********************************************************************************
        
        !!
          self.initialize_options()
        running egg_info
        creating Lollms_webui.egg-info
        error: could not create 'Lollms_webui.egg-info': Permission denied
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× python setup.py develop did not run successfully.
│ exit code: 1
╰─> [30 lines of output]
    running develop
    /opt/anaconda3/lib/python3.11/site-packages/setuptools/command/develop.py:40: EasyInstallDeprecationWarning: easy_install command is deprecated.
    !!
    
            ********************************************************************************
            Please avoid running ``setup.py`` and ``easy_install``.
            Instead, use pypa/build, pypa/installer or other
            standards-based tools.
    
            See https://github.com/pypa/setuptools/issues/917 for details.
            ********************************************************************************
    
    !!
      easy_install.initialize_options(self)
    /opt/anaconda3/lib/python3.11/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
    !!
    
            ********************************************************************************
            Please avoid running ``setup.py`` directly.
            Instead, use pypa/build, pypa/installer or other
            standards-based tools.
    
            See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
            ********************************************************************************
    
    !!
      self.initialize_options()
    running egg_info
    creating Lollms_webui.egg-info
    error: could not create 'Lollms_webui.egg-info': Permission denied
    [end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
`

**Comment by Fuckingnameless** [comment]
also getting this error during the manual venv install

`ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: '/home/vinicius/github/lollms-webui/env/lib/python3.11/site-packages/wget.py'
Check the permissions`

**Comment by Fuckingnameless** [comment]
fixed the install errors by changing ownership of files but the launch error persists

**Comment by Fuckingnameless** [comment]
ok fixed it all by changing permissions and enabling system packages into the env

it's stupid yes but i blame it on being a newbie on debian

**Comment by ParisNeo** [comment]
Hi, I am happy that you could do it.
If you want to contribute by sharing your experience in the docs/tutorials folder, you are welcome.
I was ill lately and couldn't do much of work.
