### ISSUE TITLE
Windows installation instructions need clarification

### ISSUE THREAD

**Issue by seffw** [ParisNeo/lollms-webui#523]
## Expected Behavior
If there is a Windows installer, it's good to be able to find it.

## Current Behavior
The message in the Readme is "just go to the Release page and install it"

No need for 'just' there, and where is the Release page? What does that mean? Lets not get into an exclusive club of techies who exclude everyone else.

## Steps to Reproduce
No need

## Possible Solution
Instructions to show where the Windows executable / installer is. If you talk about a 'Release' page, specify what that means. Clear instructions are what make projects grow faster. Don't become one of those forgotten projects that only die-hard techies remember.

## Context
No need

## Screenshots
If applicable, add screenshots to help explain the issue.

**Comment by ParisNeo** [comment]
Hi, the windows installer is here:
[https://github.com/ParisNeo/lollms-webui/releases/download/v9.5/lollms_setup.exe](https://github.com/ParisNeo/lollms-webui/releases/download/v9.5/lollms_setup.exe)
