### ISSUE TITLE
New fork of xtts

### ISSUE THREAD

**Issue by delebash** [ParisNeo/lollms-webui#573]
## Expected Behavior
xtts is no longer maintained but there is a new fork that seems to be updated

## Possible Solution
new repo https://github.com/idiap/coqui-ai-TTS

**Comment by ParisNeo** [comment]
Dear  @delebas, thanks for the information. I was planning to move on to another TTS server.
I'll take a look at the repo you sent me and decide if it is worth it.

Thanks alot

**Comment by delebash** [comment]
I just found another nice open-source TTS that seems active and has a nice variety of voices.  https://github.com/rhasspy/piper    Demo: https://piper.ttstool.com/
