### ISSUE TITLE
Error when trying to install whisper via stt settings tab

### ISSUE THREAD

**Issue by delebash** [ParisNeo/lollms-webui#578]
## Expected Behavior
whisper installs

## Current Behavior
Error message when you click on install whisper button

## Steps to Reproduce
1.  Goto settings page
2. Expand services zoo
3. Expand STT services
4. Click on install whisper

![image](https://github.com/user-attachments/assets/9b409e65-d126-42d4-b661-c539494e260b)

**Comment by ParisNeo** [comment]
Try now

**Comment by delebash** [comment]
tested and fixed ty.
